### Importing required libraries

In [ ]:
import numpy as np # type: ignore
import pypolar.mueller as mueller # type: ignore
np.set_printoptions(suppress=True)  # print 1e-16 as zero
from sympy import Matrix, symbols, Eq, solve # type: ignore

### Set of Linear Polarizers for Mueller matrix Polarimeter

In [136]:
L1 = mueller.op_linear_polarizer(np.radians(-45))
L2 = mueller.op_linear_polarizer(np.radians(0))
L3 = mueller.op_linear_polarizer(np.radians(45))
L4 = mueller.op_linear_polarizer(np.radians(90))

print("Mueller matrix for L1:")
print(L1)
print("Mueller matrix for L2:")
print(L2)
print("Mueller matrix for L3:")
print(L3)
print("Mueller matrix for L4:")
print(L4)

Mueller matrix for L1:
[[ 0.5  0.  -0.5  0. ]
 [ 0.   0.  -0.   0. ]
 [-0.5 -0.   0.5  0. ]
 [ 0.   0.   0.   0. ]]
Mueller matrix for L2:
[[0.5 0.5 0.  0. ]
 [0.5 0.5 0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]]
Mueller matrix for L3:
[[0.5 0.  0.5 0. ]
 [0.  0.  0.  0. ]
 [0.5 0.  0.5 0. ]
 [0.  0.  0.  0. ]]
Mueller matrix for L4:
[[ 0.5 -0.5  0.   0. ]
 [-0.5  0.5 -0.   0. ]
 [ 0.  -0.   0.   0. ]
 [ 0.   0.   0.   0. ]]


### Set of Quarter Wave Plates for Mueller matrix polarimeter

In [135]:
Q1 = mueller.op_quarter_wave_plate(np.radians(-45))
Q2 = mueller.op_quarter_wave_plate(np.radians(0))
Q3 = mueller.op_quarter_wave_plate(np.radians(45))
Q4 = mueller.op_quarter_wave_plate(np.radians(90))

print("Mueller matrix for Q1:")
print(Q1)
print("Mueller matrix for Q2:")
print(Q2)
print("Mueller matrix for Q3:")
print(Q3)
print("Mueller matrix for Q4:")
print(Q4)


Mueller matrix for Q1:
[[ 1.  0.  0.  0.]
 [ 0.  0. -0.  1.]
 [ 0. -0.  1.  0.]
 [ 0. -1. -0.  0.]]
Mueller matrix for Q2:
[[ 1.  0.  0.  0.]
 [ 0.  1.  0. -0.]
 [ 0.  0.  0.  1.]
 [ 0.  0. -1.  0.]]
Mueller matrix for Q3:
[[ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]
 [ 0.  1. -0.  0.]]
Mueller matrix for Q4:
[[ 1.  0.  0.  0.]
 [ 0.  1. -0. -0.]
 [ 0. -0.  0. -1.]
 [ 0.  0.  1.  0.]]


### Given Known Sample Mueller Matrix

In [137]:
C = mueller.op_half_wave_plate(np.radians(45))
print("Mueller matrix for Known Sample:")
print(C)

Mueller matrix for Known Sample:
[[ 1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0. -1.]]


### Combination of the Polarizer and Analyzer with Known Sample

In [ ]:
ML = L3@Q2@C@Q1@L1
print("Mueller matrix for ML:")
print(ML)

MR = L1@Q2@C@Q1@L1
print("Mueller matrix for MR:")
print(MR)

MM = L1@Q3@C@Q1@L1
print("Mueller matrix for MM:")
print(MM)

MP = L3@Q1@C@Q1@L1
print("Mueller matrix for MP:")
print(MP)

MH = L2@Q4@C@Q1@L1
print("Mueller matrix for MH:")
print(MH)

MV = L4@Q4@C@Q1@L1
print("Mueller matrix for MV:")
print(MV)



Mueller matrix for ML:
[[ 0.25  0.   -0.25  0.  ]
 [ 0.    0.   -0.    0.  ]
 [ 0.25  0.   -0.25  0.  ]
 [ 0.    0.    0.    0.  ]]
Mueller matrix for MR:
[[ 0.25  0.   -0.25  0.  ]
 [ 0.    0.   -0.    0.  ]
 [-0.25 -0.    0.25  0.  ]
 [ 0.    0.    0.    0.  ]]
Mueller matrix for MM:
[[ 0.5  0.  -0.5  0. ]
 [ 0.   0.  -0.   0. ]
 [-0.5 -0.   0.5  0. ]
 [ 0.   0.   0.   0. ]]
Mueller matrix for MP:
[[ 0.  0.  0.  0.]
 [ 0. -0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
Mueller matrix for MH:
[[ 0.25  0.   -0.25  0.  ]
 [ 0.25  0.   -0.25  0.  ]
 [ 0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.  ]]
Mueller matrix for MV:
[[ 0.25  0.   -0.25  0.  ]
 [-0.25 -0.    0.25  0.  ]
 [ 0.    0.   -0.    0.  ]
 [ 0.    0.    0.    0.  ]]


In [140]:
RL = L3@Q2@C@Q4@L1
print("Mueller matrix for RL:")
print(RL)

RR = L1@Q2@C@Q4@L1
print("Mueller matrix for RR:")
print(RR)

RM = L1@Q3@C@Q4@L1
print("Mueller matrix for RM:")
print(RM)

RP = L3@Q1@C@Q4@L1
print("Mueller matrix for RP:")
print(RP)

RH = L2@Q4@C@Q4@L1
print("Mueller matrix for RH:")
print(RH)

RV = L4@Q4@C@Q4@L1
print("Mueller matrix for RV:")
print(RV)

Mueller matrix for RL:
[[ 0.5  0.  -0.5  0. ]
 [ 0.   0.  -0.   0. ]
 [ 0.5  0.  -0.5  0. ]
 [ 0.   0.   0.   0. ]]
Mueller matrix for RR:
[[ 0.  0.  0.  0.]
 [ 0. -0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
Mueller matrix for RM:
[[ 0.25  0.   -0.25  0.  ]
 [ 0.    0.   -0.    0.  ]
 [-0.25 -0.    0.25  0.  ]
 [ 0.    0.    0.    0.  ]]
Mueller matrix for RP:
[[ 0.25  0.   -0.25  0.  ]
 [ 0.    0.   -0.    0.  ]
 [ 0.25  0.   -0.25  0.  ]
 [ 0.    0.    0.    0.  ]]
Mueller matrix for RH:
[[ 0.25  0.   -0.25  0.  ]
 [ 0.25  0.   -0.25  0.  ]
 [ 0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.  ]]
Mueller matrix for RV:
[[ 0.25  0.   -0.25  0.  ]
 [-0.25 -0.    0.25  0.  ]
 [ 0.    0.   -0.    0.  ]
 [ 0.    0.    0.    0.  ]]


In [141]:
HL = L3@Q2@C@Q2@L2
print("Mueller matrix for HL:")
print(HL)

HR = L1@Q2@C@Q2@L2
print("Mueller matrix for HR:")
print(HR)

HM = L1@Q3@C@Q2@L2
print("Mueller matrix for HM:")
print(HM)

HP = L3@Q1@C@Q2@L2
print("Mueller matrix for HP:")
print(HP)

HH = L2@Q4@C@Q2@L2
print("Mueller matrix for HH:")
print(HH)

HV = L4@Q4@C@Q2@L2
print("Mueller matrix for HV:")
print(HV)


Mueller matrix for HL:
[[0.25 0.25 0.   0.  ]
 [0.   0.   0.   0.  ]
 [0.25 0.25 0.   0.  ]
 [0.   0.   0.   0.  ]]
Mueller matrix for HR:
[[ 0.25  0.25  0.    0.  ]
 [ 0.    0.    0.    0.  ]
 [-0.25 -0.25  0.    0.  ]
 [ 0.    0.    0.    0.  ]]
Mueller matrix for HM:
[[ 0.25  0.25  0.    0.  ]
 [ 0.    0.    0.    0.  ]
 [-0.25 -0.25  0.    0.  ]
 [ 0.    0.    0.    0.  ]]
Mueller matrix for HP:
[[0.25 0.25 0.   0.  ]
 [0.   0.   0.   0.  ]
 [0.25 0.25 0.   0.  ]
 [0.   0.   0.   0.  ]]
Mueller matrix for HH:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Mueller matrix for HV:
[[ 0.5  0.5  0.   0. ]
 [-0.5 -0.5  0.   0. ]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   0.   0. ]]


In [142]:
PL = L3@Q2@C@Q3@L3
print("Mueller matrix for PL:")
print(PL)

PR = L1@Q2@C@Q3@L3
print("Mueller matrix for PR:")
print(PR)

PM = L1@Q3@C@Q3@L3
print("Mueller matrix for PM:")
print(PM)

PP = L3@Q1@C@Q3@L3
print("Mueller matrix for PP:")
print(PP)

PH = L2@Q4@C@Q3@L3
print("Mueller matrix for PH:")
print(PH)

PV = L4@Q4@C@Q3@L3
print("Mueller matrix for PV:")
print(PV)

Mueller matrix for PL:
[[0.25 0.   0.25 0.  ]
 [0.   0.   0.   0.  ]
 [0.25 0.   0.25 0.  ]
 [0.   0.   0.   0.  ]]
Mueller matrix for PR:
[[ 0.25  0.    0.25  0.  ]
 [ 0.    0.    0.    0.  ]
 [-0.25 -0.   -0.25  0.  ]
 [ 0.    0.    0.    0.  ]]
Mueller matrix for PM:
[[ 0.  0.  0.  0.]
 [ 0. -0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
Mueller matrix for PP:
[[0.5 0.  0.5 0. ]
 [0.  0.  0.  0. ]
 [0.5 0.  0.5 0. ]
 [0.  0.  0.  0. ]]
Mueller matrix for PH:
[[0.25 0.   0.25 0.  ]
 [0.25 0.   0.25 0.  ]
 [0.   0.   0.   0.  ]
 [0.   0.   0.   0.  ]]
Mueller matrix for PV:
[[ 0.25  0.    0.25  0.  ]
 [-0.25 -0.   -0.25  0.  ]
 [ 0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.  ]]


In [ ]:
LL = L3@Q2@C@Q4@L3
print("Mueller matrix for LL:")
print(LL)

LR = L1@Q2@C@Q4@L3
print("Mueller matrix for LR:")
print(LR)

LM = L1@Q3@C@Q4@L3
print("Mueller matrix for LM:")
print(LM)

LP = L3@Q1@C@Q4@L3
print("Mueller matrix for LP:")
print(LP)

LH = L2@Q4@C@Q4@L3
print("Mueller matrix for LH:")
print(LH)

LV = L4@Q4@C@Q4@L3
print("Mueller matrix for LV:")
print(LV)

In [143]:
VL = L3@Q2@C@Q4@L4
print("Mueller matrix for VL:")
print(VL)

VR = L1@Q2@C@Q4@L4
print("Mueller matrix for VR:")
print(VR)

VM = L1@Q3@C@Q4@L4
print("Mueller matrix for VM:")
print(VM)

VP = L4@Q1@C@Q4@L4
print("Mueller matrix for VP:")
print(VP)

VH = L2@Q4@C@Q4@L4
print("Mueller matrix for VH:")
print(VH)

VV = L4@Q4@C@Q4@L4
print("Mueller matrix for VV:")
print(VV)

Mueller matrix for VL:
[[ 0.25 -0.25  0.    0.  ]
 [ 0.   -0.    0.    0.  ]
 [ 0.25 -0.25  0.    0.  ]
 [ 0.    0.    0.    0.  ]]
Mueller matrix for VR:
[[ 0.25 -0.25  0.    0.  ]
 [ 0.   -0.    0.    0.  ]
 [-0.25  0.25 -0.    0.  ]
 [ 0.    0.    0.    0.  ]]
Mueller matrix for VM:
[[ 0.25 -0.25  0.    0.  ]
 [ 0.   -0.    0.    0.  ]
 [-0.25  0.25 -0.    0.  ]
 [ 0.    0.    0.    0.  ]]
Mueller matrix for VP:
[[ 0.25 -0.25  0.    0.  ]
 [-0.25  0.25 -0.    0.  ]
 [ 0.   -0.    0.    0.  ]
 [ 0.    0.    0.    0.  ]]
Mueller matrix for VH:
[[ 0.5 -0.5  0.   0. ]
 [ 0.5 -0.5  0.   0. ]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   0.   0. ]]
Mueller matrix for VV:
[[-0.  0. -0.  0.]
 [ 0. -0.  0.  0.]
 [-0.  0. -0.  0.]
 [ 0.  0.  0.  0.]]


### Set of Incidence Stokes Vectors

In [145]:
S_Ih = np.array([1,1,0,0])   # Horizonatal Stokes
print("Stokes vector for S_Ih:")
print(S_Ih)
S_Iv = np.array([1,-1,0,0])  # Vertical Stokes
print("Stokes vector for S_Iv:")
print(S_Iv)
S_Ip = np.array([1,0,1,0])   # Diagonal Stokes
print("Stokes vector for S_Ip:")
print(S_Ip)
S_Im = np.array([1,0,-1,0])  # Anti Diagonal Stokes
print("Stokes vector for S_Im:")
print(S_Im)
S_Ir = np.array([1,0,0,1])   # RCP
print("Stokes vector for S_Ir:")
print(S_Ir)
S_Il = np.array([1,0,0,-1])  # LCP
print("Stokes vector for S_Il:")
print(S_Il)

Stokes vector for S_Ih:
[1 1 0 0]
Stokes vector for S_Iv:
[ 1 -1  0  0]
Stokes vector for S_Ip:
[1 0 1 0]
Stokes vector for S_Im:
[ 1  0 -1  0]
Stokes vector for S_Ir:
[1 0 0 1]
Stokes vector for S_Il:
[ 1  0  0 -1]


# Incident Stoke's vector

In [149]:
S_i = S_Ir

### Output Stokes vectors for generator generating M

In [150]:
S_ML = np.dot(ML,S_i)
print("Output_stokes_vector for the S_ML:")
print(S_ML)

S_MR = np.dot(MR,S_i)
print("Output_stokes_vector for the S_MR:")
print(S_ML)

S_MM = np.dot(MM,S_i)
print("Output_stokes_vector for the S_MM:")
print(S_MM)

S_MP = np.dot(MP,S_i)
print("Output_stokes_vector for the S_MP:")
print(S_MP)

S_MH = np.dot(MH,S_i)
print("Output_stokes_vector for the S_MH:")
print(S_MH)

S_MV = np.dot(MV,S_i)
print("Output_stokes_vector for the S_MV:")
print(S_MV)

Output_stokes_vector for the S_ML:
[0.25 0.   0.25 0.  ]
Output_stokes_vector for the S_MR:
[0.25 0.   0.25 0.  ]
Output_stokes_vector for the S_MM:
[ 0.5  0.  -0.5  0. ]
Output_stokes_vector for the S_MP:
[0. 0. 0. 0.]
Output_stokes_vector for the S_MH:
[0.25 0.25 0.   0.  ]
Output_stokes_vector for the S_MV:
[ 0.25 -0.25  0.    0.  ]


### Output Stokes vectors for generator generating R

In [148]:
S_RL = np.dot(RL,S_i)
print("Output_stokes_vector for the S_RL:")
print(S_RL)

S_RR = np.dot(RR,S_i)
print("Output_stokes_vector for the S_RR:")
print(S_RR)

S_RM = np.dot(RM,S_i)
print("Output_stokes_vector for the S_RM:")
print(S_RM)

S_RP = np.dot(RP,S_i)
print("Output_stokes_vector for the S_RP:")
print(S_RP)

S_RH = np.dot(RH,S_i)
print("Output_stokes_vector for the S_RH:")
print(S_RH)

S_RV = np.dot(RV,S_i)
print("Output_stokes_vector for the S_RV:")
print(S_RV)

Output_stokes_vector for the S_RL:
[0.5 0.  0.5 0. ]
Output_stokes_vector for the S_RR:
[0. 0. 0. 0.]
Output_stokes_vector for the S_RM:
[ 0.25  0.   -0.25  0.  ]
Output_stokes_vector for the S_RP:
[0.25 0.   0.25 0.  ]
Output_stokes_vector for the S_RH:
[0.25 0.25 0.   0.  ]
Output_stokes_vector for the S_RV:
[ 0.25 -0.25  0.    0.  ]


### Output Stokes vectors for generator generating H

In [151]:
S_HL = np.dot(HL,S_i)
print("Output_stokes_vector for the S_HL:")
print(S_HL)

S_HR = np.dot(HR,S_i)
print("Output_stokes_vector for the S_HR:")
print(S_HR)

S_HM = np.dot(HM,S_i)
print("Output_stokes_vector for the S_HM:")
print(S_HM)

S_HP = np.dot(HP,S_i)
print("Output_stokes_vector for the S_HP:")
print(S_HP)

S_HH = np.dot(HH,S_i)
print("Output_stokes_vector for the S_HH:")
print(S_HH)

S_HV = np.dot(HV,S_i)
print("Output_stokes_vector for the S_HV:")
print(S_HV)

Output_stokes_vector for the S_HL:
[0.25 0.   0.25 0.  ]
Output_stokes_vector for the S_HR:
[ 0.25  0.   -0.25  0.  ]
Output_stokes_vector for the S_HM:
[ 0.25  0.   -0.25  0.  ]
Output_stokes_vector for the S_HP:
[0.25 0.   0.25 0.  ]
Output_stokes_vector for the S_HH:
[0. 0. 0. 0.]
Output_stokes_vector for the S_HV:
[ 0.5 -0.5  0.   0. ]


### Output Stokes vectors for generator generating P

In [152]:
S_PL = np.dot(PL,S_i)
print("Output_stokes_vector for the S_PL:")
print(S_PL)

S_PR = np.dot(PR,S_i)
print("Output_stokes_vector for the S_PR:")
print(S_PR)

S_PM = np.dot(PM,S_i)
print("Output_stokes_vector for the S_PM:")
print(S_PM)

S_PP = np.dot(PP,S_i)
print("Output_stokes_vector for the S_PP:")
print(S_PP)

S_PH = np.dot(PH,S_i)
print("Output_stokes_vector for the S_PH:")
print(S_PH)

S_PV = np.dot(PV,S_i)
print("Output_stokes_vector for the S_PV:")
print(S_PV)

Output_stokes_vector for the S_PL:
[0.25 0.   0.25 0.  ]
Output_stokes_vector for the S_PR:
[ 0.25  0.   -0.25  0.  ]
Output_stokes_vector for the S_PM:
[0. 0. 0. 0.]
Output_stokes_vector for the S_PP:
[0.5 0.  0.5 0. ]
Output_stokes_vector for the S_PH:
[0.25 0.25 0.   0.  ]
Output_stokes_vector for the S_PV:
[ 0.25 -0.25  0.    0.  ]


### Output Stokes vectors for generator generating L

In [153]:
S_LL = np.dot(LL,S_i)
print("Output_stokes_vector for the S_LL:")
print(S_LL)

S_LR = np.dot(LR,S_i)
print("Output_stokes_vector for the S_LR:")
print(S_LR)

S_LM = np.dot(LM,S_i)
print("Output_stokes_vector for the S_LM:")
print(S_LM)

S_LP = np.dot(LP,S_i)
print("Output_stokes_vector for the S_LP:")
print(S_LP)

S_LH = np.dot(LH,S_i)
print("Output_stokes_vector for the S_LH:")
print(S_LH)

S_LV = np.dot(LV,S_i)
print("Output_stokes_vector for the S_LV:")
print(S_LV)

Output_stokes_vector for the S_LL:
[0. 0. 0. 0.]
Output_stokes_vector for the S_LR:
[ 0.5  0.  -0.5  0. ]
Output_stokes_vector for the S_LM:
[ 0.25  0.   -0.25  0.  ]
Output_stokes_vector for the S_LP:
[0.25 0.   0.25 0.  ]
Output_stokes_vector for the S_LH:
[0.25 0.25 0.   0.  ]
Output_stokes_vector for the S_LV:
[ 0.25 -0.25  0.    0.  ]


### Output Stokes vectors for generator generating V

In [154]:
S_VL = np.dot(VL,S_i)
print("Output_stokes_vector for the S_VL:")
print(S_VL)

S_VR = np.dot(VR,S_i)
print("Output_stokes_vector for the S_VR:")
print(S_VR)

S_VM = np.dot(VM,S_i)
print("Output_stokes_vector for the S_VM:")
print(S_VM)

S_VP = np.dot(VP,S_i)
print("Output_stokes_vector for the S_VP:")
print(S_VP)

S_VH = np.dot(VH,S_i)
print("Output_stokes_vector for the S_VH:")
print(S_VH)

S_VV = np.dot(VV,S_i)
print("Output_stokes_vector for the S_VV:")
print(S_VV)

Output_stokes_vector for the S_VL:
[0.25 0.   0.25 0.  ]
Output_stokes_vector for the S_VR:
[ 0.25  0.   -0.25  0.  ]
Output_stokes_vector for the S_VM:
[ 0.25  0.   -0.25  0.  ]
Output_stokes_vector for the S_VP:
[ 0.25 -0.25  0.    0.  ]
Output_stokes_vector for the S_VH:
[0.5 0.5 0.  0. ]
Output_stokes_vector for the S_VV:
[-0.  0. -0.  0.]


### Defining unknown Sample Mueller matrix M (4x4)

In [167]:
M_elements = symbols('M11 M12 M13 M14 M21 M22 M23 M24 M31 M32 M33 M34 M41 M42 M43 M44')
M = Matrix(4, 4, M_elements)
print(M)

Matrix([[M11, M12, M13, M14], [M21, M22, M23, M24], [M31, M32, M33, M34], [M41, M42, M43, M44]])


#### Convert numpy matrices to SymPy matrices for symbolic multiplication

In [158]:
L1_sym = Matrix(L1)
L2_sym = Matrix(L2)
L3_sym = Matrix(L3)
L4_sym = Matrix(L4)

In [159]:
Q1_sym = Matrix(Q1)
Q2_sym = Matrix(Q2)
Q3_sym = Matrix(Q3)
Q4_sym = Matrix(Q4)


In [160]:
Si_sym = Matrix(S_i)

In [161]:
SML_sym = Matrix(S_ML)
SMR_sym = Matrix(S_MR)
SMM_sym = Matrix(S_MM)
SMP_sym = Matrix(S_MP)
SMH_sym = Matrix(S_MH)
SMV_sym = Matrix(S_MV)

In [162]:
SRL_sym = Matrix(S_RL)
SRR_sym = Matrix(S_RR)
SRM_sym = Matrix(S_RM)
SRP_sym = Matrix(S_RP)
SRH_sym = Matrix(S_RH)
SRV_sym = Matrix(S_RV)

In [163]:
SHL_sym = Matrix(S_HL)
SHR_sym = Matrix(S_HR)
SHM_sym = Matrix(S_HM)
SHP_sym = Matrix(S_HP)
SHH_sym = Matrix(S_HH)
SHV_sym = Matrix(S_HV)

In [164]:
SPL_sym = Matrix(S_PL)
SPR_sym = Matrix(S_PR)
SPM_sym = Matrix(S_PM)
SPP_sym = Matrix(S_PP)
SPH_sym = Matrix(S_PH)
SPV_sym = Matrix(S_PV)

In [165]:
SLL_sym = Matrix(S_LL)
SLR_sym = Matrix(S_LR)
SLM_sym = Matrix(S_LM)
SLP_sym = Matrix(S_LP)
SLH_sym = Matrix(S_LH)
SLV_sym = Matrix(S_LV)

In [166]:
SVL_sym = Matrix(S_VL)
SVR_sym = Matrix(S_VR)
SVM_sym = Matrix(S_VM)
SVP_sym = Matrix(S_VP)
SVH_sym = Matrix(S_VH)
SVV_sym = Matrix(S_VV)

# Generating Equations for the different sets of Generators and Analyzers 

### Equations When generator set to the M

#### Equations for ML

In [ ]:
# Define the combined symbolic matrix A = L3 * Q2 * M * Q1 * L1
A_sym = L3_sym * Q2_sym * M * Q1_sym * L1_sym

# Define equations for So = A * Si
equations = []
for i in range(4):
    equation = Eq(SML_sym[i], sum(A_sym[i, j] * Si_sym[j] for j in range(4)))
    equations.append(equation)

# Print each equation
for eq in equations:
    print(eq)

Eq(0.25, 0.25*M11 + 1.53080849893419e-17*M12 - 0.25*M13 + 1.53080849893419e-17*M21 + 9.37349864163661e-34*M22 - 1.53080849893419e-17*M23 + 0.25*M41 + 1.53080849893419e-17*M42 - 0.25*M43)
Eq(1.53080849893419e-17, 1.53080849893419e-17*M11 + 9.37349864163661e-34*M12 - 1.53080849893419e-17*M13 + 9.37349864163661e-34*M21 + 5.73961255414617e-50*M22 - 9.37349864163661e-34*M23 + 1.53080849893419e-17*M41 + 9.37349864163661e-34*M42 - 1.53080849893419e-17*M43)
Eq(0.25, 0.25*M11 + 1.53080849893419e-17*M12 - 0.25*M13 + 1.53080849893419e-17*M21 + 9.37349864163661e-34*M22 - 1.53080849893419e-17*M23 + 0.25*M41 + 1.53080849893419e-17*M42 - 0.25*M43)
True


#### Equations for MR

In [ ]:
# Define the combined symbolic matrix A = L3 * Q2 * M * Q1 * L1
A_sym = L1_sym * Q2_sym * M * Q1_sym * L1_sym

# Define equations for So = A * Si
equations = []
for i in range(4):
    equation = Eq(SMR_sym[i], sum(A_sym[i, j] * Si_sym[j] for j in range(4)))
    equations.append(equation)

# Print each equation
for eq in equations:
    print(eq)

Eq(0.25, 0.25*M11 + 1.53080849893419e-17*M12 - 0.25*M13 + 1.53080849893419e-17*M21 + 9.37349864163661e-34*M22 - 1.53080849893419e-17*M23 - 0.25*M41 - 1.53080849893419e-17*M42 + 0.25*M43)
Eq(1.53080849893419e-17, 1.53080849893419e-17*M11 + 9.37349864163661e-34*M12 - 1.53080849893419e-17*M13 + 9.37349864163661e-34*M21 + 5.73961255414617e-50*M22 - 9.37349864163661e-34*M23 - 1.53080849893419e-17*M41 - 9.37349864163661e-34*M42 + 1.53080849893419e-17*M43)
Eq(-0.25, -0.25*M11 - 1.53080849893419e-17*M12 + 0.25*M13 - 1.53080849893419e-17*M21 - 9.37349864163661e-34*M22 + 1.53080849893419e-17*M23 + 0.25*M41 + 1.53080849893419e-17*M42 - 0.25*M43)
True


#### Equations for MM

In [170]:
# Define the combined symbolic matrix A = L3 * Q2 * M * Q1 * L1
A_sym = L1_sym * Q3_sym * M * Q1_sym * L1_sym

# Define equations for S1o = A * Si
equations = []
for i in range(4):
    equation = Eq(SMM_sym[i], sum(A_sym[i, j] * Si_sym[j] for j in range(4)))
    equations.append(equation)

# Print each equation
for eq in equations:
    print(eq)

Eq(0.5, 0.25*M11 + 1.53080849893419e-17*M12 - 0.25*M13 - 1.53080849893419e-17*M21 - 9.37349864163661e-34*M22 + 1.53080849893419e-17*M23 - 0.25*M31 - 1.53080849893419e-17*M32 + 0.25*M33 - 3.06161699786838e-17*M41 - 1.87469972832732e-33*M42 + 3.06161699786838e-17*M43)
Eq(3.06161699786838e-17, 1.53080849893419e-17*M11 + 9.37349864163661e-34*M12 - 1.53080849893419e-17*M13 - 9.37349864163661e-34*M21 - 5.73961255414617e-50*M22 + 9.37349864163661e-34*M23 - 1.53080849893419e-17*M31 - 9.37349864163661e-34*M32 + 1.53080849893419e-17*M33 - 1.87469972832732e-33*M41 - 1.14792251082923e-49*M42 + 1.87469972832732e-33*M43)
Eq(-0.5, -0.25*M11 - 1.53080849893419e-17*M12 + 0.25*M13 + 1.53080849893419e-17*M21 + 9.37349864163661e-34*M22 - 1.53080849893419e-17*M23 + 0.25*M31 + 1.53080849893419e-17*M32 - 0.25*M33 + 3.06161699786838e-17*M41 + 1.87469972832732e-33*M42 - 3.06161699786838e-17*M43)
True


#### Equations for MP

In [171]:
# Define the combined symbolic matrix A = L3 * Q2 * M * Q1 * L1
A_sym = L3_sym * Q1_sym * M * Q1_sym * L1_sym

# Define equations for S1o = A * Si
equations = []
for i in range(4):
    equation = Eq(SMP_sym[i], sum(A_sym[i, j] * Si_sym[j] for j in range(4)))
    equations.append(equation)

# Print each equation
for eq in equations:
    print(eq)

Eq(0, 0.25*M11 + 1.53080849893419e-17*M12 - 0.25*M13 - 1.53080849893419e-17*M21 - 9.37349864163661e-34*M22 + 1.53080849893419e-17*M23 + 0.25*M31 + 1.53080849893419e-17*M32 - 0.25*M33 + 3.06161699786838e-17*M41 + 1.87469972832732e-33*M42 - 3.06161699786838e-17*M43)
Eq(0, 1.53080849893419e-17*M11 + 9.37349864163661e-34*M12 - 1.53080849893419e-17*M13 - 9.37349864163661e-34*M21 - 5.73961255414617e-50*M22 + 9.37349864163661e-34*M23 + 1.53080849893419e-17*M31 + 9.37349864163661e-34*M32 - 1.53080849893419e-17*M33 + 1.87469972832732e-33*M41 + 1.14792251082923e-49*M42 - 1.87469972832732e-33*M43)
Eq(0, 0.25*M11 + 1.53080849893419e-17*M12 - 0.25*M13 - 1.53080849893419e-17*M21 - 9.37349864163661e-34*M22 + 1.53080849893419e-17*M23 + 0.25*M31 + 1.53080849893419e-17*M32 - 0.25*M33 + 3.06161699786838e-17*M41 + 1.87469972832732e-33*M42 - 3.06161699786838e-17*M43)
True


#### Equations for MH

In [172]:
# Define the combined symbolic matrix A = L3 * Q2 * M * Q1 * L1
A_sym = L2_sym * Q4_sym * M * Q1_sym * L1_sym

# Define equations for S1o = A * Si
equations = []
for i in range(4):
    equation = Eq(SMH_sym[i], sum(A_sym[i, j] * Si_sym[j] for j in range(4)))
    equations.append(equation)

# Print each equation
for eq in equations:
    print(eq)

Eq(0.25, 0.25*M11 + 1.53080849893419e-17*M12 - 0.25*M13 + 0.25*M21 + 1.53080849893419e-17*M22 - 0.25*M23 - 3.06161699786838e-17*M31 - 1.87469972832732e-33*M32 + 3.06161699786838e-17*M33 - 3.06161699786838e-17*M41 - 1.87469972832732e-33*M42 + 3.06161699786838e-17*M43)
Eq(0.25, 0.25*M11 + 1.53080849893419e-17*M12 - 0.25*M13 + 0.25*M21 + 1.53080849893419e-17*M22 - 0.25*M23 - 3.06161699786838e-17*M31 - 1.87469972832732e-33*M32 + 3.06161699786838e-17*M33 - 3.06161699786838e-17*M41 - 1.87469972832732e-33*M42 + 3.06161699786838e-17*M43)
True
True


#### Equations for MV

In [176]:
# Define the combined symbolic matrix A = L3 * Q2 * M * Q1 * L1
A_sym = L4_sym * Q4_sym * M * Q1_sym * L1_sym

# Define equations for S1o = A * Si
equations = []
for i in range(4):
    equation = Eq(SMV_sym[i], sum(A_sym[i, j] * Si_sym[j] for j in range(4)))
    equations.append(equation)

# Print each equation
for eq in equations:
    print(eq)

Eq(0.25, 0.25*M11 + 1.53080849893419e-17*M12 - 0.25*M13 - 0.25*M21 - 1.53080849893419e-17*M22 + 0.25*M23 + 3.06161699786838e-17*M31 + 1.87469972832732e-33*M32 - 3.06161699786838e-17*M33)
Eq(-0.25, -0.25*M11 - 1.53080849893419e-17*M12 + 0.25*M13 + 0.25*M21 + 1.53080849893419e-17*M22 - 0.25*M23 - 3.06161699786838e-17*M31 - 1.87469972832732e-33*M32 + 3.06161699786838e-17*M33)
Eq(3.06161699786838e-17, 3.06161699786838e-17*M11 + 1.87469972832732e-33*M12 - 3.06161699786838e-17*M13 - 3.06161699786838e-17*M21 - 1.87469972832732e-33*M22 + 3.06161699786838e-17*M23 + 3.74939945665464e-33*M31 + 2.29584502165847e-49*M32 - 3.74939945665464e-33*M33)
True


#### Equations for RL

In [177]:
# Define the combined symbolic matrix A = L3 * Q2 * M * Q1 * L1
A_sym = L3_sym * Q2_sym * M * Q4_sym * L1_sym

# Define equations for S1o = A * Si
equations = []
for i in range(4):
    equation = Eq(SRL_sym[i], sum(A_sym[i, j] * Si_sym[j] for j in range(4)))
    equations.append(equation)

# Print each equation
for eq in equations:
    print(eq)

Eq(0.5, 0.25*M11 + 4.59242549680257e-17*M12 - 5.62409918498197e-33*M13 - 0.25*M14 + 1.53080849893419e-17*M21 + 2.81204959249098e-33*M22 - 3.4437675324877e-49*M23 - 1.53080849893419e-17*M24 + 0.25*M41 + 4.59242549680257e-17*M42 - 5.62409918498197e-33*M43 - 0.25*M44)
Eq(3.06161699786838e-17, 1.53080849893419e-17*M11 + 2.81204959249098e-33*M12 - 3.4437675324877e-49*M13 - 1.53080849893419e-17*M14 + 9.37349864163661e-34*M21 + 1.72188376624385e-49*M22 - 2.10869944283432e-65*M23 - 9.37349864163661e-34*M24 + 1.53080849893419e-17*M41 + 2.81204959249098e-33*M42 - 3.4437675324877e-49*M43 - 1.53080849893419e-17*M44)
Eq(0.5, 0.25*M11 + 4.59242549680257e-17*M12 - 5.62409918498197e-33*M13 - 0.25*M14 + 1.53080849893419e-17*M21 + 2.81204959249098e-33*M22 - 3.4437675324877e-49*M23 - 1.53080849893419e-17*M24 + 0.25*M41 + 4.59242549680257e-17*M42 - 5.62409918498197e-33*M43 - 0.25*M44)
True


#### Equations for RR

In [178]:
# Define the combined symbolic matrix A = L3 * Q2 * M * Q1 * L1
A_sym = L1_sym * Q2_sym * M * Q4_sym * L1_sym

# Define equations for S1o = A * Si
equations = []
for i in range(4):
    equation = Eq(SRR_sym[i], sum(A_sym[i, j] * Si_sym[j] for j in range(4)))
    equations.append(equation)

# Print each equation
for eq in equations:
    print(eq)

Eq(0, 0.25*M11 + 4.59242549680257e-17*M12 - 5.62409918498197e-33*M13 - 0.25*M14 + 1.53080849893419e-17*M21 + 2.81204959249098e-33*M22 - 3.4437675324877e-49*M23 - 1.53080849893419e-17*M24 - 0.25*M41 - 4.59242549680257e-17*M42 + 5.62409918498197e-33*M43 + 0.25*M44)
Eq(0, 1.53080849893419e-17*M11 + 2.81204959249098e-33*M12 - 3.4437675324877e-49*M13 - 1.53080849893419e-17*M14 + 9.37349864163661e-34*M21 + 1.72188376624385e-49*M22 - 2.10869944283432e-65*M23 - 9.37349864163661e-34*M24 - 1.53080849893419e-17*M41 - 2.81204959249098e-33*M42 + 3.4437675324877e-49*M43 + 1.53080849893419e-17*M44)
Eq(0, -0.25*M11 - 4.59242549680257e-17*M12 + 5.62409918498197e-33*M13 + 0.25*M14 - 1.53080849893419e-17*M21 - 2.81204959249098e-33*M22 + 3.4437675324877e-49*M23 + 1.53080849893419e-17*M24 + 0.25*M41 + 4.59242549680257e-17*M42 - 5.62409918498197e-33*M43 - 0.25*M44)
True


#### Equations for RM

In [179]:
# Define the combined symbolic matrix A = L3 * Q2 * M * Q1 * L1
A_sym = L1_sym * Q3_sym * M * Q4_sym * L1_sym

# Define equations for S1o = A * Si
equations = []
for i in range(4):
    equation = Eq(SRM_sym[i], sum(A_sym[i, j] * Si_sym[j] for j in range(4)))
    equations.append(equation)

# Print each equation
for eq in equations:
    print(eq)

Eq(0.25, 0.25*M11 + 4.59242549680257e-17*M12 - 5.62409918498197e-33*M13 - 0.25*M14 - 1.53080849893419e-17*M21 - 2.81204959249098e-33*M22 + 3.4437675324877e-49*M23 + 1.53080849893419e-17*M24 - 0.25*M31 - 4.59242549680257e-17*M32 + 5.62409918498197e-33*M33 + 0.25*M34 - 3.06161699786838e-17*M41 - 5.62409918498197e-33*M42 + 6.8875350649754e-49*M43 + 3.06161699786838e-17*M44)
Eq(1.53080849893419e-17, 1.53080849893419e-17*M11 + 2.81204959249098e-33*M12 - 3.4437675324877e-49*M13 - 1.53080849893419e-17*M14 - 9.37349864163661e-34*M21 - 1.72188376624385e-49*M22 + 2.10869944283432e-65*M23 + 9.37349864163661e-34*M24 - 1.53080849893419e-17*M31 - 2.81204959249098e-33*M32 + 3.4437675324877e-49*M33 + 1.53080849893419e-17*M34 - 1.87469972832732e-33*M41 - 3.4437675324877e-49*M42 + 4.21739888566864e-65*M43 + 1.87469972832732e-33*M44)
Eq(-0.25, -0.25*M11 - 4.59242549680257e-17*M12 + 5.62409918498197e-33*M13 + 0.25*M14 + 1.53080849893419e-17*M21 + 2.81204959249098e-33*M22 - 3.4437675324877e-49*M23 - 1.5308

#### Equations for RP

In [180]:
# Define the combined symbolic matrix A = L3 * Q2 * M * Q1 * L1
A_sym = L3_sym * Q1_sym * M * Q4_sym * L1_sym

# Define equations for S1o = A * Si
equations = []
for i in range(4):
    equation = Eq(SRP_sym[i], sum(A_sym[i, j] * Si_sym[j] for j in range(4)))
    equations.append(equation)

# Print each equation
for eq in equations:
    print(eq)

Eq(0.25, 0.25*M11 + 4.59242549680257e-17*M12 - 5.62409918498197e-33*M13 - 0.25*M14 - 1.53080849893419e-17*M21 - 2.81204959249098e-33*M22 + 3.4437675324877e-49*M23 + 1.53080849893419e-17*M24 + 0.25*M31 + 4.59242549680257e-17*M32 - 5.62409918498197e-33*M33 - 0.25*M34 + 3.06161699786838e-17*M41 + 5.62409918498197e-33*M42 - 6.8875350649754e-49*M43 - 3.06161699786838e-17*M44)
Eq(1.53080849893419e-17, 1.53080849893419e-17*M11 + 2.81204959249098e-33*M12 - 3.4437675324877e-49*M13 - 1.53080849893419e-17*M14 - 9.37349864163661e-34*M21 - 1.72188376624385e-49*M22 + 2.10869944283432e-65*M23 + 9.37349864163661e-34*M24 + 1.53080849893419e-17*M31 + 2.81204959249098e-33*M32 - 3.4437675324877e-49*M33 - 1.53080849893419e-17*M34 + 1.87469972832732e-33*M41 + 3.4437675324877e-49*M42 - 4.21739888566864e-65*M43 - 1.87469972832732e-33*M44)
Eq(0.25, 0.25*M11 + 4.59242549680257e-17*M12 - 5.62409918498197e-33*M13 - 0.25*M14 - 1.53080849893419e-17*M21 - 2.81204959249098e-33*M22 + 3.4437675324877e-49*M23 + 1.530808

#### Equations for RH

In [181]:
# Define the combined symbolic matrix A = L3 * Q2 * M * Q1 * L1
A_sym = L2_sym * Q4_sym * M * Q4_sym * L1_sym

# Define equations for S1o = A * Si
equations = []
for i in range(4):
    equation = Eq(SRH_sym[i], sum(A_sym[i, j] * Si_sym[j] for j in range(4)))
    equations.append(equation)

# Print each equation
for eq in equations:
    print(eq)

Eq(0.25, 0.25*M11 + 4.59242549680257e-17*M12 - 5.62409918498197e-33*M13 - 0.25*M14 + 0.25*M21 + 4.59242549680257e-17*M22 - 5.62409918498197e-33*M23 - 0.25*M24 - 3.06161699786838e-17*M31 - 5.62409918498197e-33*M32 + 6.8875350649754e-49*M33 + 3.06161699786838e-17*M34 - 3.06161699786838e-17*M41 - 5.62409918498197e-33*M42 + 6.8875350649754e-49*M43 + 3.06161699786838e-17*M44)
Eq(0.25, 0.25*M11 + 4.59242549680257e-17*M12 - 5.62409918498197e-33*M13 - 0.25*M14 + 0.25*M21 + 4.59242549680257e-17*M22 - 5.62409918498197e-33*M23 - 0.25*M24 - 3.06161699786838e-17*M31 - 5.62409918498197e-33*M32 + 6.8875350649754e-49*M33 + 3.06161699786838e-17*M34 - 3.06161699786838e-17*M41 - 5.62409918498197e-33*M42 + 6.8875350649754e-49*M43 + 3.06161699786838e-17*M44)
True
True


#### Equations for RV

In [182]:
# Define the combined symbolic matrix A = L3 * Q2 * M * Q1 * L1
A_sym = L4_sym * Q4_sym * M * Q4_sym * L1_sym

# Define equations for S1o = A * Si
equations = []
for i in range(4):
    equation = Eq(SRV_sym[i], sum(A_sym[i, j] * Si_sym[j] for j in range(4)))
    equations.append(equation)

# Print each equation
for eq in equations:
    print(eq)

Eq(0.25, 0.25*M11 + 4.59242549680257e-17*M12 - 5.62409918498197e-33*M13 - 0.25*M14 - 0.25*M21 - 4.59242549680257e-17*M22 + 5.62409918498197e-33*M23 + 0.25*M24 + 3.06161699786838e-17*M31 + 5.62409918498197e-33*M32 - 6.8875350649754e-49*M33 - 3.06161699786838e-17*M34)
Eq(-0.25, -0.25*M11 - 4.59242549680257e-17*M12 + 5.62409918498197e-33*M13 + 0.25*M14 + 0.25*M21 + 4.59242549680257e-17*M22 - 5.62409918498197e-33*M23 - 0.25*M24 - 3.06161699786838e-17*M31 - 5.62409918498197e-33*M32 + 6.8875350649754e-49*M33 + 3.06161699786838e-17*M34)
Eq(3.06161699786838e-17, 3.06161699786838e-17*M11 + 5.62409918498197e-33*M12 - 6.8875350649754e-49*M13 - 3.06161699786838e-17*M14 - 3.06161699786838e-17*M21 - 5.62409918498197e-33*M22 + 6.8875350649754e-49*M23 + 3.06161699786838e-17*M24 + 3.74939945665464e-33*M31 + 6.8875350649754e-49*M32 - 8.43479777133728e-65*M33 - 3.74939945665464e-33*M34)
True


#### Equations for HL

In [183]:
# Define the combined symbolic matrix A = L3 * Q2 * M * Q1 * L1
A_sym = L3_sym * Q2_sym * M * Q2_sym * L2_sym

# Define equations for S1o = A * Si
equations = []
for i in range(4):
    equation = Eq(SHL_sym[i], sum(A_sym[i, j] * Si_sym[j] for j in range(4)))
    equations.append(equation)

# Print each equation
for eq in equations:
    print(eq)

Eq(0.25, 0.25*M11 + 0.25*M12 + 1.53080849893419e-17*M21 + 1.53080849893419e-17*M22 + 0.25*M41 + 0.25*M42)
Eq(1.53080849893419e-17, 1.53080849893419e-17*M11 + 1.53080849893419e-17*M12 + 9.37349864163661e-34*M21 + 9.37349864163661e-34*M22 + 1.53080849893419e-17*M41 + 1.53080849893419e-17*M42)
Eq(0.25, 0.25*M11 + 0.25*M12 + 1.53080849893419e-17*M21 + 1.53080849893419e-17*M22 + 0.25*M41 + 0.25*M42)
True


#### Equations for HR

In [184]:
# Define the combined symbolic matrix A = L3 * Q2 * M * Q1 * L1
A_sym = L1_sym * Q2_sym * M * Q2_sym * L2_sym

# Define equations for S1o = A * Si
equations = []
for i in range(4):
    equation = Eq(SHR_sym[i], sum(A_sym[i, j] * Si_sym[j] for j in range(4)))
    equations.append(equation)

# Print each equation
for eq in equations:
    print(eq)

Eq(0.25, 0.25*M11 + 0.25*M12 + 1.53080849893419e-17*M21 + 1.53080849893419e-17*M22 - 0.25*M41 - 0.25*M42)
Eq(1.53080849893419e-17, 1.53080849893419e-17*M11 + 1.53080849893419e-17*M12 + 9.37349864163661e-34*M21 + 9.37349864163661e-34*M22 - 1.53080849893419e-17*M41 - 1.53080849893419e-17*M42)
Eq(-0.25, -0.25*M11 - 0.25*M12 - 1.53080849893419e-17*M21 - 1.53080849893419e-17*M22 + 0.25*M41 + 0.25*M42)
True


#### Equations for HM

In [185]:
# Define the combined symbolic matrix A = L3 * Q2 * M * Q1 * L1
A_sym = L3_sym * Q3_sym * M * Q2_sym * L2_sym

# Define equations for S1o = A * Si
equations = []
for i in range(4):
    equation = Eq(SHM_sym[i], sum(A_sym[i, j] * Si_sym[j] for j in range(4)))
    equations.append(equation)

# Print each equation
for eq in equations:
    print(eq)

Eq(0.25, 0.25*M11 + 0.25*M12 + 1.53080849893419e-17*M21 + 1.53080849893419e-17*M22 + 0.25*M31 + 0.25*M32)
Eq(1.53080849893419e-17, 1.53080849893419e-17*M11 + 1.53080849893419e-17*M12 + 9.37349864163661e-34*M21 + 9.37349864163661e-34*M22 + 1.53080849893419e-17*M31 + 1.53080849893419e-17*M32)
Eq(-0.25, 0.25*M11 + 0.25*M12 + 1.53080849893419e-17*M21 + 1.53080849893419e-17*M22 + 0.25*M31 + 0.25*M32)
True


#### Equations for HP

In [186]:
# Define the combined symbolic matrix A = L3 * Q2 * M * Q1 * L1
A_sym = L3_sym * Q1_sym * M * Q2_sym * L2_sym

# Define equations for S1o = A * Si
equations = []
for i in range(4):
    equation = Eq(SHP_sym[i], sum(A_sym[i, j] * Si_sym[j] for j in range(4)))
    equations.append(equation)

# Print each equation
for eq in equations:
    print(eq)

Eq(0.25, 0.25*M11 + 0.25*M12 - 1.53080849893419e-17*M21 - 1.53080849893419e-17*M22 + 0.25*M31 + 0.25*M32 + 3.06161699786838e-17*M41 + 3.06161699786838e-17*M42)
Eq(1.53080849893419e-17, 1.53080849893419e-17*M11 + 1.53080849893419e-17*M12 - 9.37349864163661e-34*M21 - 9.37349864163661e-34*M22 + 1.53080849893419e-17*M31 + 1.53080849893419e-17*M32 + 1.87469972832732e-33*M41 + 1.87469972832732e-33*M42)
Eq(0.25, 0.25*M11 + 0.25*M12 - 1.53080849893419e-17*M21 - 1.53080849893419e-17*M22 + 0.25*M31 + 0.25*M32 + 3.06161699786838e-17*M41 + 3.06161699786838e-17*M42)
True


#### Equations for HH

In [187]:
# Define the combined symbolic matrix A = L3 * Q2 * M * Q1 * L1
A_sym = L2_sym * Q4_sym * M * Q2_sym * L2_sym

# Define equations for S1o = A * Si
equations = []
for i in range(4):
    equation = Eq(SHH_sym[i], sum(A_sym[i, j] * Si_sym[j] for j in range(4)))
    equations.append(equation)

# Print each equation
for eq in equations:
    print(eq)

Eq(0, 0.25*M11 + 0.25*M12 + 0.25*M21 + 0.25*M22 - 3.06161699786838e-17*M31 - 3.06161699786838e-17*M32 - 3.06161699786838e-17*M41 - 3.06161699786838e-17*M42)
Eq(0, 0.25*M11 + 0.25*M12 + 0.25*M21 + 0.25*M22 - 3.06161699786838e-17*M31 - 3.06161699786838e-17*M32 - 3.06161699786838e-17*M41 - 3.06161699786838e-17*M42)
True
True


#### Equations for HV

In [188]:
# Define the combined symbolic matrix A = L3 * Q2 * M * Q1 * L1
A_sym = L4_sym * Q4_sym * M * Q2_sym * L2_sym

# Define equations for S1o = A * Si
equations = []
for i in range(4):
    equation = Eq(SHV_sym[i], sum(A_sym[i, j] * Si_sym[j] for j in range(4)))
    equations.append(equation)

# Print each equation
for eq in equations:
    print(eq)

Eq(0.5, 0.25*M11 + 0.25*M12 - 0.25*M21 - 0.25*M22 + 3.06161699786838e-17*M31 + 3.06161699786838e-17*M32)
Eq(-0.5, -0.25*M11 - 0.25*M12 + 0.25*M21 + 0.25*M22 - 3.06161699786838e-17*M31 - 3.06161699786838e-17*M32)
Eq(6.12323399573677e-17, 3.06161699786838e-17*M11 + 3.06161699786838e-17*M12 - 3.06161699786838e-17*M21 - 3.06161699786838e-17*M22 + 3.74939945665464e-33*M31 + 3.74939945665464e-33*M32)
True


#### Equations for PL

In [189]:
# Define the combined symbolic matrix A = L3 * Q2 * M * Q1 * L1
A_sym = L3_sym * Q2_sym * M * Q3_sym * L3_sym

# Define equations for S1o = A * Si
equations = []
for i in range(4):
    equation = Eq(SPL_sym[i], sum(A_sym[i, j] * Si_sym[j] for j in range(4)))
    equations.append(equation)

# Print each equation
for eq in equations:
    print(eq)

Eq(0.25, 0.25*M11 + 1.53080849893419e-17*M12 + 0.25*M13 + 1.53080849893419e-17*M21 + 9.37349864163661e-34*M22 + 1.53080849893419e-17*M23 + 0.25*M41 + 1.53080849893419e-17*M42 + 0.25*M43)
Eq(1.53080849893419e-17, 1.53080849893419e-17*M11 + 9.37349864163661e-34*M12 + 1.53080849893419e-17*M13 + 9.37349864163661e-34*M21 + 5.73961255414617e-50*M22 + 9.37349864163661e-34*M23 + 1.53080849893419e-17*M41 + 9.37349864163661e-34*M42 + 1.53080849893419e-17*M43)
Eq(0.25, 0.25*M11 + 1.53080849893419e-17*M12 + 0.25*M13 + 1.53080849893419e-17*M21 + 9.37349864163661e-34*M22 + 1.53080849893419e-17*M23 + 0.25*M41 + 1.53080849893419e-17*M42 + 0.25*M43)
True


#### Equations for PR

In [190]:
# Define the combined symbolic matrix A = L3 * Q2 * M * Q1 * L1
A_sym = L1_sym * Q2_sym * M * Q3_sym * L3_sym

# Define equations for S1o = A * Si
equations = []
for i in range(4):
    equation = Eq(SPR_sym[i], sum(A_sym[i, j] * Si_sym[j] for j in range(4)))
    equations.append(equation)

# Print each equation
for eq in equations:
    print(eq)

Eq(0.25, 0.25*M11 + 1.53080849893419e-17*M12 + 0.25*M13 + 1.53080849893419e-17*M21 + 9.37349864163661e-34*M22 + 1.53080849893419e-17*M23 - 0.25*M41 - 1.53080849893419e-17*M42 - 0.25*M43)
Eq(1.53080849893419e-17, 1.53080849893419e-17*M11 + 9.37349864163661e-34*M12 + 1.53080849893419e-17*M13 + 9.37349864163661e-34*M21 + 5.73961255414617e-50*M22 + 9.37349864163661e-34*M23 - 1.53080849893419e-17*M41 - 9.37349864163661e-34*M42 - 1.53080849893419e-17*M43)
Eq(-0.25, -0.25*M11 - 1.53080849893419e-17*M12 - 0.25*M13 - 1.53080849893419e-17*M21 - 9.37349864163661e-34*M22 - 1.53080849893419e-17*M23 + 0.25*M41 + 1.53080849893419e-17*M42 + 0.25*M43)
True


#### Equations for PM

In [191]:
# Define the combined symbolic matrix A = L3 * Q2 * M * Q1 * L1
A_sym = L1_sym * Q3_sym * M * Q3_sym * L3_sym

# Define equations for S1o = A * Si
equations = []
for i in range(4):
    equation = Eq(SPM_sym[i], sum(A_sym[i, j] * Si_sym[j] for j in range(4)))
    equations.append(equation)

# Print each equation
for eq in equations:
    print(eq)

Eq(0, 0.25*M11 + 1.53080849893419e-17*M12 + 0.25*M13 - 1.53080849893419e-17*M21 - 9.37349864163661e-34*M22 - 1.53080849893419e-17*M23 - 0.25*M31 - 1.53080849893419e-17*M32 - 0.25*M33 - 3.06161699786838e-17*M41 - 1.87469972832732e-33*M42 - 3.06161699786838e-17*M43)
Eq(0, 1.53080849893419e-17*M11 + 9.37349864163661e-34*M12 + 1.53080849893419e-17*M13 - 9.37349864163661e-34*M21 - 5.73961255414617e-50*M22 - 9.37349864163661e-34*M23 - 1.53080849893419e-17*M31 - 9.37349864163661e-34*M32 - 1.53080849893419e-17*M33 - 1.87469972832732e-33*M41 - 1.14792251082923e-49*M42 - 1.87469972832732e-33*M43)
Eq(0, -0.25*M11 - 1.53080849893419e-17*M12 - 0.25*M13 + 1.53080849893419e-17*M21 + 9.37349864163661e-34*M22 + 1.53080849893419e-17*M23 + 0.25*M31 + 1.53080849893419e-17*M32 + 0.25*M33 + 3.06161699786838e-17*M41 + 1.87469972832732e-33*M42 + 3.06161699786838e-17*M43)
True


#### Equations for PP

In [192]:
# Define the combined symbolic matrix A = L3 * Q2 * M * Q1 * L1
A_sym = L3_sym * Q1_sym * M * Q3_sym * L3_sym

# Define equations for S1o = A * Si
equations = []
for i in range(4):
    equation = Eq(SPP_sym[i], sum(A_sym[i, j] * Si_sym[j] for j in range(4)))
    equations.append(equation)

# Print each equation
for eq in equations:
    print(eq)

Eq(0.5, 0.25*M11 + 1.53080849893419e-17*M12 + 0.25*M13 - 1.53080849893419e-17*M21 - 9.37349864163661e-34*M22 - 1.53080849893419e-17*M23 + 0.25*M31 + 1.53080849893419e-17*M32 + 0.25*M33 + 3.06161699786838e-17*M41 + 1.87469972832732e-33*M42 + 3.06161699786838e-17*M43)
Eq(3.06161699786838e-17, 1.53080849893419e-17*M11 + 9.37349864163661e-34*M12 + 1.53080849893419e-17*M13 - 9.37349864163661e-34*M21 - 5.73961255414617e-50*M22 - 9.37349864163661e-34*M23 + 1.53080849893419e-17*M31 + 9.37349864163661e-34*M32 + 1.53080849893419e-17*M33 + 1.87469972832732e-33*M41 + 1.14792251082923e-49*M42 + 1.87469972832732e-33*M43)
Eq(0.5, 0.25*M11 + 1.53080849893419e-17*M12 + 0.25*M13 - 1.53080849893419e-17*M21 - 9.37349864163661e-34*M22 - 1.53080849893419e-17*M23 + 0.25*M31 + 1.53080849893419e-17*M32 + 0.25*M33 + 3.06161699786838e-17*M41 + 1.87469972832732e-33*M42 + 3.06161699786838e-17*M43)
True


#### Equations for PH

In [193]:
# Define the combined symbolic matrix A = L3 * Q2 * M * Q1 * L1
A_sym = L2_sym * Q4_sym * M * Q3_sym * L3_sym

# Define equations for S1o = A * Si
equations = []
for i in range(4):
    equation = Eq(SPH_sym[i], sum(A_sym[i, j] * Si_sym[j] for j in range(4)))
    equations.append(equation)

# Print each equation
for eq in equations:
    print(eq)

Eq(0.25, 0.25*M11 + 1.53080849893419e-17*M12 + 0.25*M13 + 0.25*M21 + 1.53080849893419e-17*M22 + 0.25*M23 - 3.06161699786838e-17*M31 - 1.87469972832732e-33*M32 - 3.06161699786838e-17*M33 - 3.06161699786838e-17*M41 - 1.87469972832732e-33*M42 - 3.06161699786838e-17*M43)
Eq(0.25, 0.25*M11 + 1.53080849893419e-17*M12 + 0.25*M13 + 0.25*M21 + 1.53080849893419e-17*M22 + 0.25*M23 - 3.06161699786838e-17*M31 - 1.87469972832732e-33*M32 - 3.06161699786838e-17*M33 - 3.06161699786838e-17*M41 - 1.87469972832732e-33*M42 - 3.06161699786838e-17*M43)
True
True


#### Equations for PV

In [194]:
# Define the combined symbolic matrix A = L3 * Q2 * M * Q1 * L1
A_sym = L4_sym * Q4_sym * M * Q3_sym * L3_sym

# Define equations for S1o = A * Si
equations = []
for i in range(4):
    equation = Eq(SPV_sym[i], sum(A_sym[i, j] * Si_sym[j] for j in range(4)))
    equations.append(equation)

# Print each equation
for eq in equations:
    print(eq)

Eq(0.25, 0.25*M11 + 1.53080849893419e-17*M12 + 0.25*M13 - 0.25*M21 - 1.53080849893419e-17*M22 - 0.25*M23 + 3.06161699786838e-17*M31 + 1.87469972832732e-33*M32 + 3.06161699786838e-17*M33)
Eq(-0.25, -0.25*M11 - 1.53080849893419e-17*M12 - 0.25*M13 + 0.25*M21 + 1.53080849893419e-17*M22 + 0.25*M23 - 3.06161699786838e-17*M31 - 1.87469972832732e-33*M32 - 3.06161699786838e-17*M33)
Eq(3.06161699786838e-17, 3.06161699786838e-17*M11 + 1.87469972832732e-33*M12 + 3.06161699786838e-17*M13 - 3.06161699786838e-17*M21 - 1.87469972832732e-33*M22 - 3.06161699786838e-17*M23 + 3.74939945665464e-33*M31 + 2.29584502165847e-49*M32 + 3.74939945665464e-33*M33)
True


#### Equations for LL

In [195]:
# Define the combined symbolic matrix A = L3 * Q2 * M * Q1 * L1
A_sym = L3_sym * Q2_sym * M * Q4_sym * L3_sym

# Define equations for S1o = A * Si
equations = []
for i in range(4):
    equation = Eq(SLL_sym[i], sum(A_sym[i, j] * Si_sym[j] for j in range(4)))
    equations.append(equation)

# Print each equation
for eq in equations:
    print(eq)

Eq(0, 0.25*M11 - 1.53080849893419e-17*M12 + 1.87469972832732e-33*M13 + 0.25*M14 + 1.53080849893419e-17*M21 - 9.37349864163661e-34*M22 + 1.14792251082923e-49*M23 + 1.53080849893419e-17*M24 + 0.25*M41 - 1.53080849893419e-17*M42 + 1.87469972832732e-33*M43 + 0.25*M44)
Eq(0, 1.53080849893419e-17*M11 - 9.37349864163661e-34*M12 + 1.14792251082923e-49*M13 + 1.53080849893419e-17*M14 + 9.37349864163661e-34*M21 - 5.73961255414617e-50*M22 + 7.02899814278107e-66*M23 + 9.37349864163661e-34*M24 + 1.53080849893419e-17*M41 - 9.37349864163661e-34*M42 + 1.14792251082923e-49*M43 + 1.53080849893419e-17*M44)
Eq(0, 0.25*M11 - 1.53080849893419e-17*M12 + 1.87469972832732e-33*M13 + 0.25*M14 + 1.53080849893419e-17*M21 - 9.37349864163661e-34*M22 + 1.14792251082923e-49*M23 + 1.53080849893419e-17*M24 + 0.25*M41 - 1.53080849893419e-17*M42 + 1.87469972832732e-33*M43 + 0.25*M44)
True


#### Equations for LR

In [196]:
# Define the combined symbolic matrix A = L3 * Q2 * M * Q1 * L1
A_sym = L1_sym * Q2_sym * M * Q4_sym * L3_sym

# Define equations for S1o = A * Si
equations = []
for i in range(4):
    equation = Eq(SLR_sym[i], sum(A_sym[i, j] * Si_sym[j] for j in range(4)))
    equations.append(equation)

# Print each equation
for eq in equations:
    print(eq)

Eq(0.5, 0.25*M11 - 1.53080849893419e-17*M12 + 1.87469972832732e-33*M13 + 0.25*M14 + 1.53080849893419e-17*M21 - 9.37349864163661e-34*M22 + 1.14792251082923e-49*M23 + 1.53080849893419e-17*M24 - 0.25*M41 + 1.53080849893419e-17*M42 - 1.87469972832732e-33*M43 - 0.25*M44)
Eq(3.06161699786838e-17, 1.53080849893419e-17*M11 - 9.37349864163661e-34*M12 + 1.14792251082923e-49*M13 + 1.53080849893419e-17*M14 + 9.37349864163661e-34*M21 - 5.73961255414617e-50*M22 + 7.02899814278107e-66*M23 + 9.37349864163661e-34*M24 - 1.53080849893419e-17*M41 + 9.37349864163661e-34*M42 - 1.14792251082923e-49*M43 - 1.53080849893419e-17*M44)
Eq(-0.5, -0.25*M11 + 1.53080849893419e-17*M12 - 1.87469972832732e-33*M13 - 0.25*M14 - 1.53080849893419e-17*M21 + 9.37349864163661e-34*M22 - 1.14792251082923e-49*M23 - 1.53080849893419e-17*M24 + 0.25*M41 - 1.53080849893419e-17*M42 + 1.87469972832732e-33*M43 + 0.25*M44)
True


#### Equations for LM

In [197]:
# Define the combined symbolic matrix A = L3 * Q2 * M * Q1 * L1
A_sym = L1_sym * Q3_sym * M * Q4_sym * L3_sym

# Define equations for S1o = A * Si
equations = []
for i in range(4):
    equation = Eq(SLM_sym[i], sum(A_sym[i, j] * Si_sym[j] for j in range(4)))
    equations.append(equation)

# Print each equation
for eq in equations:
    print(eq)

Eq(0.25, 0.25*M11 - 1.53080849893419e-17*M12 + 1.87469972832732e-33*M13 + 0.25*M14 - 1.53080849893419e-17*M21 + 9.37349864163661e-34*M22 - 1.14792251082923e-49*M23 - 1.53080849893419e-17*M24 - 0.25*M31 + 1.53080849893419e-17*M32 - 1.87469972832732e-33*M33 - 0.25*M34 - 3.06161699786838e-17*M41 + 1.87469972832732e-33*M42 - 2.29584502165847e-49*M43 - 3.06161699786838e-17*M44)
Eq(1.53080849893419e-17, 1.53080849893419e-17*M11 - 9.37349864163661e-34*M12 + 1.14792251082923e-49*M13 + 1.53080849893419e-17*M14 - 9.37349864163661e-34*M21 + 5.73961255414617e-50*M22 - 7.02899814278107e-66*M23 - 9.37349864163661e-34*M24 - 1.53080849893419e-17*M31 + 9.37349864163661e-34*M32 - 1.14792251082923e-49*M33 - 1.53080849893419e-17*M34 - 1.87469972832732e-33*M41 + 1.14792251082923e-49*M42 - 1.40579962855621e-65*M43 - 1.87469972832732e-33*M44)
Eq(-0.25, -0.25*M11 + 1.53080849893419e-17*M12 - 1.87469972832732e-33*M13 - 0.25*M14 + 1.53080849893419e-17*M21 - 9.37349864163661e-34*M22 + 1.14792251082923e-49*M23 + 

#### Equations for LP

In [198]:
# Define the combined symbolic matrix A = L3 * Q2 * M * Q1 * L1
A_sym = L3_sym * Q1_sym * M * Q4_sym * L3_sym

# Define equations for S1o = A * Si
equations = []
for i in range(4):
    equation = Eq(SLP_sym[i], sum(A_sym[i, j] * Si_sym[j] for j in range(4)))
    equations.append(equation)

# Print each equation
for eq in equations:
    print(eq)

Eq(0.25, 0.25*M11 - 1.53080849893419e-17*M12 + 1.87469972832732e-33*M13 + 0.25*M14 - 1.53080849893419e-17*M21 + 9.37349864163661e-34*M22 - 1.14792251082923e-49*M23 - 1.53080849893419e-17*M24 + 0.25*M31 - 1.53080849893419e-17*M32 + 1.87469972832732e-33*M33 + 0.25*M34 + 3.06161699786838e-17*M41 - 1.87469972832732e-33*M42 + 2.29584502165847e-49*M43 + 3.06161699786838e-17*M44)
Eq(1.53080849893419e-17, 1.53080849893419e-17*M11 - 9.37349864163661e-34*M12 + 1.14792251082923e-49*M13 + 1.53080849893419e-17*M14 - 9.37349864163661e-34*M21 + 5.73961255414617e-50*M22 - 7.02899814278107e-66*M23 - 9.37349864163661e-34*M24 + 1.53080849893419e-17*M31 - 9.37349864163661e-34*M32 + 1.14792251082923e-49*M33 + 1.53080849893419e-17*M34 + 1.87469972832732e-33*M41 - 1.14792251082923e-49*M42 + 1.40579962855621e-65*M43 + 1.87469972832732e-33*M44)
Eq(0.25, 0.25*M11 - 1.53080849893419e-17*M12 + 1.87469972832732e-33*M13 + 0.25*M14 - 1.53080849893419e-17*M21 + 9.37349864163661e-34*M22 - 1.14792251082923e-49*M23 - 1.

#### Equations for LH

In [199]:
# Define the combined symbolic matrix A = L3 * Q2 * M * Q1 * L1
A_sym = L2_sym * Q4_sym * M * Q4_sym * L3_sym

# Define equations for S1o = A * Si
equations = []
for i in range(4):
    equation = Eq(SLH_sym[i], sum(A_sym[i, j] * Si_sym[j] for j in range(4)))
    equations.append(equation)

# Print each equation
for eq in equations:
    print(eq)

Eq(0.25, 0.25*M11 - 1.53080849893419e-17*M12 + 1.87469972832732e-33*M13 + 0.25*M14 + 0.25*M21 - 1.53080849893419e-17*M22 + 1.87469972832732e-33*M23 + 0.25*M24 - 3.06161699786838e-17*M31 + 1.87469972832732e-33*M32 - 2.29584502165847e-49*M33 - 3.06161699786838e-17*M34 - 3.06161699786838e-17*M41 + 1.87469972832732e-33*M42 - 2.29584502165847e-49*M43 - 3.06161699786838e-17*M44)
Eq(0.25, 0.25*M11 - 1.53080849893419e-17*M12 + 1.87469972832732e-33*M13 + 0.25*M14 + 0.25*M21 - 1.53080849893419e-17*M22 + 1.87469972832732e-33*M23 + 0.25*M24 - 3.06161699786838e-17*M31 + 1.87469972832732e-33*M32 - 2.29584502165847e-49*M33 - 3.06161699786838e-17*M34 - 3.06161699786838e-17*M41 + 1.87469972832732e-33*M42 - 2.29584502165847e-49*M43 - 3.06161699786838e-17*M44)
True
True


#### Equations for LV

In [200]:
# Define the combined symbolic matrix A = L3 * Q2 * M * Q1 * L1
A_sym = L4_sym * Q4_sym * M * Q4_sym * L3_sym

# Define equations for S1o = A * Si
equations = []
for i in range(4):
    equation = Eq(SLV_sym[i], sum(A_sym[i, j] * Si_sym[j] for j in range(4)))
    equations.append(equation)

# Print each equation
for eq in equations:
    print(eq)

Eq(0.25, 0.25*M11 - 1.53080849893419e-17*M12 + 1.87469972832732e-33*M13 + 0.25*M14 - 0.25*M21 + 1.53080849893419e-17*M22 - 1.87469972832732e-33*M23 - 0.25*M24 + 3.06161699786838e-17*M31 - 1.87469972832732e-33*M32 + 2.29584502165847e-49*M33 + 3.06161699786838e-17*M34)
Eq(-0.25, -0.25*M11 + 1.53080849893419e-17*M12 - 1.87469972832732e-33*M13 - 0.25*M14 + 0.25*M21 - 1.53080849893419e-17*M22 + 1.87469972832732e-33*M23 + 0.25*M24 - 3.06161699786838e-17*M31 + 1.87469972832732e-33*M32 - 2.29584502165847e-49*M33 - 3.06161699786838e-17*M34)
Eq(3.06161699786838e-17, 3.06161699786838e-17*M11 - 1.87469972832732e-33*M12 + 2.29584502165847e-49*M13 + 3.06161699786838e-17*M14 - 3.06161699786838e-17*M21 + 1.87469972832732e-33*M22 - 2.29584502165847e-49*M23 - 3.06161699786838e-17*M24 + 3.74939945665464e-33*M31 - 2.29584502165847e-49*M32 + 2.81159925711243e-65*M33 + 3.74939945665464e-33*M34)
True


#### Equations for VL

In [201]:
# Define the combined symbolic matrix A = L3 * Q2 * M * Q1 * L1
A_sym = L3_sym * Q2_sym * M * Q4_sym * L4_sym

# Define equations for S1o = A * Si
equations = []
for i in range(4):
    equation = Eq(SVL_sym[i], sum(A_sym[i, j] * Si_sym[j] for j in range(4)))
    equations.append(equation)

# Print each equation
for eq in equations:
    print(eq)

Eq(0.25, 0.25*M11 - 0.25*M12 + 3.06161699786838e-17*M13 + 1.53080849893419e-17*M21 - 1.53080849893419e-17*M22 + 1.87469972832732e-33*M23 + 0.25*M41 - 0.25*M42 + 3.06161699786838e-17*M43)
Eq(1.53080849893419e-17, 1.53080849893419e-17*M11 - 1.53080849893419e-17*M12 + 1.87469972832732e-33*M13 + 9.37349864163661e-34*M21 - 9.37349864163661e-34*M22 + 1.14792251082923e-49*M23 + 1.53080849893419e-17*M41 - 1.53080849893419e-17*M42 + 1.87469972832732e-33*M43)
Eq(0.25, 0.25*M11 - 0.25*M12 + 3.06161699786838e-17*M13 + 1.53080849893419e-17*M21 - 1.53080849893419e-17*M22 + 1.87469972832732e-33*M23 + 0.25*M41 - 0.25*M42 + 3.06161699786838e-17*M43)
True


#### Equations for VR

In [202]:
# Define the combined symbolic matrix A = L3 * Q2 * M * Q1 * L1
A_sym = L1_sym * Q2_sym * M * Q4_sym * L4_sym

# Define equations for S1o = A * Si
equations = []
for i in range(4):
    equation = Eq(SVR_sym[i], sum(A_sym[i, j] * Si_sym[j] for j in range(4)))
    equations.append(equation)

# Print each equation
for eq in equations:
    print(eq)

Eq(0.25, 0.25*M11 - 0.25*M12 + 3.06161699786838e-17*M13 + 1.53080849893419e-17*M21 - 1.53080849893419e-17*M22 + 1.87469972832732e-33*M23 - 0.25*M41 + 0.25*M42 - 3.06161699786838e-17*M43)
Eq(1.53080849893419e-17, 1.53080849893419e-17*M11 - 1.53080849893419e-17*M12 + 1.87469972832732e-33*M13 + 9.37349864163661e-34*M21 - 9.37349864163661e-34*M22 + 1.14792251082923e-49*M23 - 1.53080849893419e-17*M41 + 1.53080849893419e-17*M42 - 1.87469972832732e-33*M43)
Eq(-0.25, -0.25*M11 + 0.25*M12 - 3.06161699786838e-17*M13 - 1.53080849893419e-17*M21 + 1.53080849893419e-17*M22 - 1.87469972832732e-33*M23 + 0.25*M41 - 0.25*M42 + 3.06161699786838e-17*M43)
True


#### Equations for VM

In [203]:
# Define the combined symbolic matrix A = L3 * Q2 * M * Q1 * L1
A_sym = L1_sym * Q3_sym * M * Q4_sym * L4_sym

# Define equations for S1o = A * Si
equations = []
for i in range(4):
    equation = Eq(SVM_sym[i], sum(A_sym[i, j] * Si_sym[j] for j in range(4)))
    equations.append(equation)

# Print each equation
for eq in equations:
    print(eq)

Eq(0.25, 0.25*M11 - 0.25*M12 + 3.06161699786838e-17*M13 - 1.53080849893419e-17*M21 + 1.53080849893419e-17*M22 - 1.87469972832732e-33*M23 - 0.25*M31 + 0.25*M32 - 3.06161699786838e-17*M33 - 3.06161699786838e-17*M41 + 3.06161699786838e-17*M42 - 3.74939945665464e-33*M43)
Eq(1.53080849893419e-17, 1.53080849893419e-17*M11 - 1.53080849893419e-17*M12 + 1.87469972832732e-33*M13 - 9.37349864163661e-34*M21 + 9.37349864163661e-34*M22 - 1.14792251082923e-49*M23 - 1.53080849893419e-17*M31 + 1.53080849893419e-17*M32 - 1.87469972832732e-33*M33 - 1.87469972832732e-33*M41 + 1.87469972832732e-33*M42 - 2.29584502165847e-49*M43)
Eq(-0.25, -0.25*M11 + 0.25*M12 - 3.06161699786838e-17*M13 + 1.53080849893419e-17*M21 - 1.53080849893419e-17*M22 + 1.87469972832732e-33*M23 + 0.25*M31 - 0.25*M32 + 3.06161699786838e-17*M33 + 3.06161699786838e-17*M41 - 3.06161699786838e-17*M42 + 3.74939945665464e-33*M43)
True


#### Equations for VP

In [204]:
# Define the combined symbolic matrix A = L3 * Q2 * M * Q1 * L1
A_sym = L4_sym * Q1_sym * M * Q4_sym * L4_sym

# Define equations for S1o = A * Si
equations = []
for i in range(4):
    equation = Eq(SVP_sym[i], sum(A_sym[i, j] * Si_sym[j] for j in range(4)))
    equations.append(equation)

# Print each equation
for eq in equations:
    print(eq)

Eq(0.25, 0.25*M11 - 0.25*M12 + 3.06161699786838e-17*M13 - 2.81204959249098e-33*M21 + 2.81204959249098e-33*M22 - 3.4437675324877e-49*M23 + 4.59242549680257e-17*M31 - 4.59242549680257e-17*M32 + 5.62409918498197e-33*M33 - 0.25*M41 + 0.25*M42 - 3.06161699786838e-17*M43)
Eq(-0.25, -0.25*M11 + 0.25*M12 - 3.06161699786838e-17*M13 + 2.81204959249098e-33*M21 - 2.81204959249098e-33*M22 + 3.4437675324877e-49*M23 - 4.59242549680257e-17*M31 + 4.59242549680257e-17*M32 - 5.62409918498197e-33*M33 + 0.25*M41 - 0.25*M42 + 3.06161699786838e-17*M43)
Eq(3.06161699786838e-17, 3.06161699786838e-17*M11 - 3.06161699786838e-17*M12 + 3.74939945665464e-33*M13 - 3.4437675324877e-49*M21 + 3.4437675324877e-49*M22 - 4.21739888566864e-65*M23 + 5.62409918498197e-33*M31 - 5.62409918498197e-33*M32 + 6.8875350649754e-49*M33 - 3.06161699786838e-17*M41 + 3.06161699786838e-17*M42 - 3.74939945665464e-33*M43)
True


#### Equations for VH

In [205]:
# Define the combined symbolic matrix A = L3 * Q2 * M * Q1 * L1
A_sym = L2_sym * Q4_sym * M * Q4_sym * L4_sym

# Define equations for S1o = A * Si
equations = []
for i in range(4):
    equation = Eq(SVH_sym[i], sum(A_sym[i, j] * Si_sym[j] for j in range(4)))
    equations.append(equation)

# Print each equation
for eq in equations:
    print(eq)

Eq(0.5, 0.25*M11 - 0.25*M12 + 3.06161699786838e-17*M13 + 0.25*M21 - 0.25*M22 + 3.06161699786838e-17*M23 - 3.06161699786838e-17*M31 + 3.06161699786838e-17*M32 - 3.74939945665464e-33*M33 - 3.06161699786838e-17*M41 + 3.06161699786838e-17*M42 - 3.74939945665464e-33*M43)
Eq(0.5, 0.25*M11 - 0.25*M12 + 3.06161699786838e-17*M13 + 0.25*M21 - 0.25*M22 + 3.06161699786838e-17*M23 - 3.06161699786838e-17*M31 + 3.06161699786838e-17*M32 - 3.74939945665464e-33*M33 - 3.06161699786838e-17*M41 + 3.06161699786838e-17*M42 - 3.74939945665464e-33*M43)
True
True


#### Equations for VV

In [206]:
# Define the combined symbolic matrix A = L3 * Q2 * M * Q1 * L1
A_sym = L4_sym * Q4_sym * M * Q4_sym * L4_sym

# Define equations for S1o = A * Si
equations = []
for i in range(4):
    equation = Eq(SVV_sym[i], sum(A_sym[i, j] * Si_sym[j] for j in range(4)))
    equations.append(equation)

# Print each equation
for eq in equations:
    print(eq)

Eq(-3.74939945665464e-33, 0.25*M11 - 0.25*M12 + 3.06161699786838e-17*M13 - 0.25*M21 + 0.25*M22 - 3.06161699786838e-17*M23 + 3.06161699786838e-17*M31 - 3.06161699786838e-17*M32 + 3.74939945665464e-33*M33)
Eq(3.74939945665464e-33, -0.25*M11 + 0.25*M12 - 3.06161699786838e-17*M13 + 0.25*M21 - 0.25*M22 + 3.06161699786838e-17*M23 - 3.06161699786838e-17*M31 + 3.06161699786838e-17*M32 - 3.74939945665464e-33*M33)
Eq(-4.59169004331693e-49, 3.06161699786838e-17*M11 - 3.06161699786838e-17*M12 + 3.74939945665464e-33*M13 - 3.06161699786838e-17*M21 + 3.06161699786838e-17*M22 - 3.74939945665464e-33*M23 + 3.74939945665464e-33*M31 - 3.74939945665464e-33*M32 + 4.59169004331693e-49*M33)
True
